# Generated by Django 2.1.7 on 2019-07-29 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='collab_artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('song_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('submission_date', models.DateTimeField(auto_now=True)),
                ('studio', models.CharField(max_length=25)),
                ('artist', models.CharField(default='Brozy', max_length=25)),
                ('cover_image', models.ImageField(upload_to='songCoverFolder')),
                ('featuring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Music.collab_artist')),
            ],
        ),
    ]
