# Generated by Django 2.1.7 on 2019-07-31 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0002_auto_20190729_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='song_file',
            field=models.FileField(default=None, upload_to='media/songFileFolder',null=True),
            preserve_default=False,
        ),
    ]
